import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import Link from "next/link";

import { ClerkProvider } from "@clerk/nextjs";
import { TopNav } from "./_components/topnav";
export const metadata: Metadata = {
  title: "Fixe",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};



export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${GeistSans.variable}`}>
        <body className="min-h-screen bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
          <TopNav />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
